// This file is generated by scripts/generate-addon-proxy.ts. Do not edit by hand.
import type {
  AddonForwardResponse,
  AddonServerToClientEventName,
  AddonServerToClientEventArgs,
  AddonServerToClientSDKWebsocketMessage,
} from '@ogi-sdk/connect';

export type AddonForwardResponseMessage<Event extends AddonServerToClientEventName> = Omit<
  AddonServerToClientSDKWebsocketMessage<'forward-response', Event>,
  'args'
> & {
  args: AddonForwardResponse<Event>;
};

export type DeferredAddonEvent =
  'search'
  | 'setup'
  | 'library-search'
  | 'request-dl'
  | 'catalog'
  | 'task-run'
  | 'game-details'
  | 'check-for-updates';

type AddonProxyMethod<Event extends AddonServerToClientEventName> = (
  ...args: AddonServerToClientEventArgs[Event]
) => Promise<AddonForwardResponse<Event>['args']>;

type CamelCaseEvent<Event extends string> =
  Event extends `${infer Head}-${infer Tail}`
    ? `${Head}${Capitalize<CamelCaseEvent<Tail>>}`
    : Event;

export type AddonProxy = {
  [Event in AddonServerToClientEventName as CamelCaseEvent<Event>]: AddonProxyMethod<Event>;
};

type SendToAddon = <Event extends AddonServerToClientEventName>(
  addonId: string,
  event: Event,
  ...args: AddonServerToClientEventArgs[Event]
) => Promise<AddonForwardResponseMessage<Event>>;

type DeferToAddon = <Event extends AddonServerToClientEventName>(
  addonId: string,
  event: Event,
  args: AddonServerToClientEventArgs[Event]
) => Promise<AddonForwardResponse<Event>['args']>;

const toCamelCaseEvent = (event: string): string => {
  return event.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
};

export const addonEventAliases = [
  'authenticate',
  'configure',
  'config-update',
  'launch-app',
  'search',
  'setup',
  'response',
  'library-search',
  'check-for-updates',
  'task-run',
  'game-details',
  'request-dl',
  'catalog',
].reduce(
  (aliases, event) => {
    aliases[toCamelCaseEvent(event)] = event as AddonServerToClientEventName;
    return aliases;
  },
  {} as Record<string, AddonServerToClientEventName>
);

const deferredAddonEvents = new Set<AddonServerToClientEventName>([
  'search',
  'setup',
  'library-search',
  'request-dl',
  'catalog',
  'task-run',
  'game-details',
  'check-for-updates',
] as AddonServerToClientEventName[]);

export const createAddonProxy = (
  addonId: string,
  sendToAddon: SendToAddon,
  deferToAddon: DeferToAddon
): AddonProxy => {
  return new Proxy({} as AddonProxy, {
    get(_target, property) {
      if (typeof property !== 'string') return undefined;

      const event = addonEventAliases[property];
      if (!event) return undefined;

      return async (...args: AddonServerToClientEventArgs[typeof event]) => {
        if (deferredAddonEvents.has(event)) {
          return deferToAddon(addonId, event, args);
        }

        const response = await sendToAddon(addonId, event, ...args);
        if (response.statusError) {
          throw new Error(response.statusError);
        }
        return response.args.args;
      };
    },
  });
};
