import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createLogger, LOGGER_PREFIXES } from '@ogi/logger';
import { addonProtocol } from '../../connection/lib/protocol';

const logger = createLogger(LOGGER_PREFIXES.clientKit);

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDir, '..');
const outputPath = join(packageRoot, 'lib', '_generated', 'addon-proxy.ts');

const entries = Object.keys(addonProtocol.serverToAddon);
const deferredEntries = [
  'search',
  'setup',
  'library-search',
  'request-dl',
  'catalog',
  'task-run',
  'game-details',
  'check-for-updates',
];

const generated = `// This file is generated by scripts/generate-addon-proxy.ts. Do not edit by hand.
import { NetworkError, type ValidationError } from '@ogi/errors';
import type {
  AddonForwardResponse,
  AddonServerToClientEventName,
  AddonServerToClientEventArgs,
  AddonServerToClientSDKWebsocketMessage,
  ConfigurationFile,
  ConnectedAddonInfo,
} from '@ogi-sdk/connect';
import { Effect } from 'effect';

export type AddonForwardResponseMessage<Event extends AddonServerToClientEventName> = Omit<
  AddonServerToClientSDKWebsocketMessage<'forward-response', Event>,
  'args'
> & {
  args: AddonForwardResponse<Event>;
};

export type DeferredAddonEvent =
${deferredEntries.map((event, index) => `  ${index === 0 ? '' : '| '}'${event}'`).join('\n')};

type EffectAddonProxyMethod<
  Event extends AddonServerToClientEventName,
  E,
> = (
  ...args: AddonServerToClientEventArgs[Event]
) => Effect.Effect<
  AddonForwardResponse<Event>['args'],
  NetworkError | ValidationError | E
>;

type CamelCaseEvent<Event extends string> =
  Event extends \`\${infer Head}-\${infer Tail}\`
    ? \`\${Head}\${Capitalize<CamelCaseEvent<Tail>>}\`
    : Event;

export type AddonProxyMetadata = {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly version: string;
  readonly author: string;
  readonly repository: string;
  readonly storefronts: string[];
  readonly eventsAvailable: string[];
  readonly configTemplate: ConfigurationFile | undefined;
  readonly icon: string | undefined;
  readonly iconPath: string | undefined;
};

export type EffectAddonProxy<E = never> = AddonProxyMetadata & {
  [Event in AddonServerToClientEventName as CamelCaseEvent<Event>]: EffectAddonProxyMethod<Event, E>;
};

type SendToAddon = <Event extends AddonServerToClientEventName>(
  addonId: string,
  event: Event,
  ...args: AddonServerToClientEventArgs[Event]
) => Effect.Effect<
  AddonForwardResponseMessage<Event>,
  NetworkError | ValidationError
>;

type DeferToAddon<E> = <Event extends AddonServerToClientEventName>(
  addonId: string,
  event: Event,
  args: AddonServerToClientEventArgs[Event]
) => Effect.Effect<
  AddonForwardResponse<Event>['args'],
  NetworkError | ValidationError | E
>;

type GetAddonInfo = (addonId: string) => ConnectedAddonInfo | undefined;

const emptyAddonInfo = (addonId: string): ConnectedAddonInfo => ({
  id: addonId,
  name: '',
  description: '',
  version: '',
  author: '',
  repository: '',
  storefronts: [],
  eventsAvailable: [],
});

const addonMetadataGetters: Record<
  keyof AddonProxyMetadata,
  (info: ConnectedAddonInfo) => AddonProxyMetadata[keyof AddonProxyMetadata]
> = {
  id: (info) => info.id,
  name: (info) => info.name,
  description: (info) => info.description ?? '',
  version: (info) => info.version ?? '',
  author: (info) => info.author ?? '',
  repository: (info) => info.repository ?? '',
  storefronts: (info) => info.storefronts ?? [],
  eventsAvailable: (info) => info.eventsAvailable,
  configTemplate: (info) => info.configTemplate,
  icon: (info) => info.icon,
  iconPath: (info) => info.iconPath,
};

const toCamelCaseEvent = (event: string): string => {
  return event.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
};

export const addonEventAliases = [
${entries.map((event) => `  '${event}',`).join('\n')}
].reduce(
  (aliases, event) => {
    aliases[toCamelCaseEvent(event)] = event as AddonServerToClientEventName;
    return aliases;
  },
  Object.create(null) as Record<string, AddonServerToClientEventName>
);

const deferredAddonEvents = new Set<AddonServerToClientEventName>([
${deferredEntries.map((event) => `  '${event}',`).join('\n')}
] as AddonServerToClientEventName[]);

export const createEffectAddonProxy = <E>(
  addonId: string,
  sendToAddon: SendToAddon,
  deferToAddon: DeferToAddon<E>,
  getAddonInfo: GetAddonInfo
): EffectAddonProxy<E> => {
  return new Proxy({} as EffectAddonProxy<E>, {
    get(_target, property) {
      if (typeof property !== 'string') return undefined;

      if (property in addonMetadataGetters) {
        const info = getAddonInfo(addonId) ?? emptyAddonInfo(addonId);
        return addonMetadataGetters[property as keyof AddonProxyMetadata](info);
      }

      if (!Object.hasOwn(addonEventAliases, property)) return undefined;
      const event = addonEventAliases[property]!;

      return (...args: AddonServerToClientEventArgs[typeof event]) => {
        if (deferredAddonEvents.has(event)) {
          return deferToAddon(addonId, event, args);
        }

        return sendToAddon(addonId, event, ...args).pipe(
          Effect.flatMap((response) =>
            response.statusError
              ? Effect.fail(new NetworkError({ message: response.statusError }))
              : Effect.succeed(response.args.args)
          )
        );
      };
    },
  });
};
`;

await Bun.write(outputPath, generated);
const format = Bun.spawn(['bunx', 'biome', 'check', '--write', outputPath], {
  stdout: 'inherit',
  stderr: 'inherit',
});
if ((await format.exited) !== 0) {
  throw new Error(`Failed to format ${outputPath}`);
}
logger.sync.info(`Generated ${outputPath}`);
