import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { addonProtocol } from '../../connection/lib/protocol';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDir, '..');
const outputPath = join(packageRoot, 'lib', '_generated', 'addon-proxy.ts');

const entries = Object.keys(addonProtocol.serverToAddon);
const deferredEntries = [
  'search',
  'setup',
  'library-search',
  'request-dl',
  'catalog',
  'task-run',
  'game-details',
  'check-for-updates',
];

const generated = `// This file is generated by scripts/generate-addon-proxy.ts. Do not edit by hand.
import type {
  AddonForwardResponse,
  AddonServerToClientEventName,
  AddonServerToClientEventArgs,
  AddonServerToClientSDKWebsocketMessage,
} from '@ogi-sdk/connect';

export type AddonForwardResponseMessage<Event extends AddonServerToClientEventName> = Omit<
  AddonServerToClientSDKWebsocketMessage<'forward-response', Event>,
  'args'
> & {
  args: AddonForwardResponse<Event>;
};

export type DeferredAddonEvent =
${deferredEntries.map((event, index) => `  ${index === 0 ? '' : '| '}'${event}'`).join('\n')};

type AddonProxyMethod<Event extends AddonServerToClientEventName> = (
  ...args: AddonServerToClientEventArgs[Event]
) => Promise<AddonForwardResponse<Event>['args']>;

type CamelCaseEvent<Event extends string> =
  Event extends \`\${infer Head}-\${infer Tail}\`
    ? \`\${Head}\${Capitalize<CamelCaseEvent<Tail>>}\`
    : Event;

export type AddonProxy = {
  [Event in AddonServerToClientEventName as CamelCaseEvent<Event>]: AddonProxyMethod<Event>;
};

type SendToAddon = <Event extends AddonServerToClientEventName>(
  addonId: string,
  event: Event,
  ...args: AddonServerToClientEventArgs[Event]
) => Promise<AddonForwardResponseMessage<Event>>;

type DeferToAddon = <Event extends AddonServerToClientEventName>(
  addonId: string,
  event: Event,
  args: AddonServerToClientEventArgs[Event]
) => Promise<AddonForwardResponse<Event>['args']>;

const toCamelCaseEvent = (event: string): string => {
  return event.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
};

export const addonEventAliases = [
${entries.map((event) => `  '${event}',`).join('\n')}
].reduce(
  (aliases, event) => {
    aliases[toCamelCaseEvent(event)] = event as AddonServerToClientEventName;
    return aliases;
  },
  {} as Record<string, AddonServerToClientEventName>
);

const deferredAddonEvents = new Set<AddonServerToClientEventName>([
${deferredEntries.map((event) => `  '${event}',`).join('\n')}
] as AddonServerToClientEventName[]);

export const createAddonProxy = (
  addonId: string,
  sendToAddon: SendToAddon,
  deferToAddon: DeferToAddon
): AddonProxy => {
  return new Proxy({} as AddonProxy, {
    get(_target, property) {
      if (typeof property !== 'string') return undefined;

      const event = addonEventAliases[property];
      if (!event) return undefined;

      return async (...args: AddonServerToClientEventArgs[typeof event]) => {
        if (deferredAddonEvents.has(event)) {
          return deferToAddon(addonId, event, args);
        }

        const response = await sendToAddon(addonId, event, ...args);
        if (response.statusError) {
          throw new Error(response.statusError);
        }
        return response.args.args;
      };
    },
  });
};
`;

await Bun.write(outputPath, generated);
console.log(`Generated ${outputPath}`);
