import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { addonProtocol } from '../../connection/lib/protocol';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDir, '..');
const outputPath = join(packageRoot, 'lib', '_generated', 'addon-proxy.ts');

const entries = Object.keys(addonProtocol.serverToAddon);
const deferredEntries = [
  'search',
  'setup',
  'library-search',
  'request-dl',
  'catalog',
  'task-run',
  'game-details',
  'check-for-updates',
];

const generated = `// This file is generated by scripts/generate-addon-proxy.ts. Do not edit by hand.
import type {
  AddonForwardResponse,
  AddonServerToClientEventName,
  AddonServerToClientEventArgs,
  AddonServerToClientSDKWebsocketMessage,
  ConfigurationFile,
  ConnectedAddonInfo,
} from '@ogi-sdk/connect';

export type AddonForwardResponseMessage<Event extends AddonServerToClientEventName> = Omit<
  AddonServerToClientSDKWebsocketMessage<'forward-response', Event>,
  'args'
> & {
  args: AddonForwardResponse<Event>;
};

export type DeferredAddonEvent =
${deferredEntries.map((event, index) => `  ${index === 0 ? '' : '| '}'${event}'`).join('\n')};

type AddonProxyMethod<Event extends AddonServerToClientEventName> = (
  ...args: AddonServerToClientEventArgs[Event]
) => Promise<AddonForwardResponse<Event>['args']>;

type CamelCaseEvent<Event extends string> =
  Event extends \`\${infer Head}-\${infer Tail}\`
    ? \`\${Head}\${Capitalize<CamelCaseEvent<Tail>>}\`
    : Event;

export type AddonProxyMetadata = {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly version: string;
  readonly author: string;
  readonly repository: string;
  readonly storefronts: string[];
  readonly eventsAvailable: string[];
  readonly configTemplate: ConfigurationFile | undefined;
  readonly icon: string | undefined;
  readonly iconPath: string | undefined;
};

export type AddonProxy = AddonProxyMetadata & {
  [Event in AddonServerToClientEventName as CamelCaseEvent<Event>]: AddonProxyMethod<Event>;
};

type SendToAddon = <Event extends AddonServerToClientEventName>(
  addonId: string,
  event: Event,
  ...args: AddonServerToClientEventArgs[Event]
) => Promise<AddonForwardResponseMessage<Event>>;

type DeferToAddon = <Event extends AddonServerToClientEventName>(
  addonId: string,
  event: Event,
  args: AddonServerToClientEventArgs[Event]
) => Promise<AddonForwardResponse<Event>['args']>;

type GetAddonInfo = (addonId: string) => ConnectedAddonInfo | undefined;

const emptyAddonInfo = (addonId: string): ConnectedAddonInfo => ({
  id: addonId,
  name: '',
  description: '',
  version: '',
  author: '',
  repository: '',
  storefronts: [],
  eventsAvailable: [],
});

const addonMetadataGetters: Record<
  keyof AddonProxyMetadata,
  (info: ConnectedAddonInfo) => AddonProxyMetadata[keyof AddonProxyMetadata]
> = {
  id: (info) => info.id,
  name: (info) => info.name,
  description: (info) => info.description ?? '',
  version: (info) => info.version ?? '',
  author: (info) => info.author ?? '',
  repository: (info) => info.repository ?? '',
  storefronts: (info) => info.storefronts ?? [],
  eventsAvailable: (info) => info.eventsAvailable,
  configTemplate: (info) => info.configTemplate,
  icon: (info) => info.icon,
  iconPath: (info) => info.iconPath,
};

const toCamelCaseEvent = (event: string): string => {
  return event.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
};

export const addonEventAliases = [
${entries.map((event) => `  '${event}',`).join('\n')}
].reduce(
  (aliases, event) => {
    aliases[toCamelCaseEvent(event)] = event as AddonServerToClientEventName;
    return aliases;
  },
  {} as Record<string, AddonServerToClientEventName>
);

const deferredAddonEvents = new Set<AddonServerToClientEventName>([
${deferredEntries.map((event) => `  '${event}',`).join('\n')}
] as AddonServerToClientEventName[]);

export const createAddonProxy = (
  addonId: string,
  sendToAddon: SendToAddon,
  deferToAddon: DeferToAddon,
  getAddonInfo: GetAddonInfo
): AddonProxy => {
  return new Proxy({} as AddonProxy, {
    get(_target, property) {
      if (typeof property !== 'string') return undefined;

      if (property in addonMetadataGetters) {
        const info = getAddonInfo(addonId) ?? emptyAddonInfo(addonId);
        return addonMetadataGetters[property as keyof AddonProxyMetadata](info);
      }

      const event = addonEventAliases[property];
      if (!event) return undefined;

      return async (...args: AddonServerToClientEventArgs[typeof event]) => {
        if (deferredAddonEvents.has(event)) {
          return deferToAddon(addonId, event, args);
        }

        const response = await sendToAddon(addonId, event, ...args);
        if (response.statusError) {
          throw new Error(response.statusError);
        }
        return response.args.args;
      };
    },
  });
};
`;

await Bun.write(outputPath, generated);
console.log(`Generated ${outputPath}`);
