// This file is generated by scripts/generate-event-proxy.ts. Do not edit by hand.
import type {
  EventListenerTypes,
  LibraryInfo,
  OGIAddonServerSentEvent,
  WebsocketMessageClient,
  WebsocketMessageServer,
} from 'ogi-addon';
import type { ConfigurationFile } from 'ogi-addon/config';

type ArgsBeforeEventResponse<T extends unknown[]> = T extends [
  ...infer Args,
  unknown,
]
  ? Args
  : T;

type ListenerEventArgs<Event extends keyof EventListenerTypes> =
  ArgsBeforeEventResponse<Parameters<EventListenerTypes[Event]>>;

export type TaskRunArgs = {
  manifest?: Record<string, unknown>;
  downloadPath?: string;
  name?: string;
  taskName?: string;
  libraryInfo?: LibraryInfo;
  deferID?: string;
};

export type ServerEventArgs = {
  'authenticate': [config?: unknown];
  'configure': [config: ConfigurationFile];
  'config-update': [config: ConfigurationFile];
  'launch-app': ListenerEventArgs<'launch-app'>;
  'search': ListenerEventArgs<'search'>;
  'setup': ListenerEventArgs<'setup'>;
  'response': [id: string, response?: unknown, statusError?: string];
  'library-search': ListenerEventArgs<'library-search'>;
  'check-for-updates': ListenerEventArgs<'check-for-updates'>;
  'task-run': [task: TaskRunArgs];
  'game-details': ListenerEventArgs<'game-details'>;
  'request-dl': ListenerEventArgs<'request-dl'>;
  'catalog': ListenerEventArgs<'catalog'>;
};

type SendEventProxyMethod<Event extends OGIAddonServerSentEvent> = (
  ...args: ServerEventArgs[Event]
) => Promise<WebsocketMessageClient>;

type CamelCaseEvent<Event extends string> =
  Event extends `${infer Head}-${infer Tail}`
    ? `${Head}${Capitalize<CamelCaseEvent<Tail>>}`
    : Event;

type SendEventProxyMethods = {
  [Event in OGIAddonServerSentEvent as CamelCaseEvent<Event>]: SendEventProxyMethod<Event>;
};

export type SendEventProxy = SendEventProxyMethods & {
  noResponse: SendEventProxyMethods;
};

type EventMessagePackers = {
  [Event in OGIAddonServerSentEvent]: (
    args: ServerEventArgs[Event]
  ) => Omit<WebsocketMessageServer, 'event'>;
};

const eventMessagePackers: EventMessagePackers = {
  'authenticate': ([config]) => ({ args: config }),
  'configure': ([config]) => ({ args: config }),
  'config-update': ([config]) => ({ args: config }),
  'launch-app': ([data]) => ({ args: data }),
  'search': ([query]) => ({ args: query }),
  'setup': ([data]) => ({ args: data }),
  'response': ([id, response, statusError]) => ({ id, args: response, statusError }),
  'library-search': ([query]) => ({ args: query }),
  'check-for-updates': ([data]) => ({ args: data }),
  'task-run': ([task]) => ({ args: task }),
  'game-details': ([details]) => ({ args: details }),
  'request-dl': ([appID, info]) => ({ args: { appID, info } }),
  'catalog': () => ({ args: undefined }),
};

const toCamelCaseEvent = (event: string): string => {
  return event.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
};

export const eventAliases = Object.keys(eventMessagePackers).reduce(
  (aliases, event) => {
    aliases[toCamelCaseEvent(event)] = event as OGIAddonServerSentEvent;
    return aliases;
  },
  {} as Record<string, OGIAddonServerSentEvent>
);

export const buildEventMessage = <Event extends OGIAddonServerSentEvent>(
  event: Event,
  args: ServerEventArgs[Event]
): WebsocketMessageServer => {
  return {
    event,
    ...eventMessagePackers[event](args),
  };
};
