// This file is generated by scripts/generate-event-proxy.ts. Do not edit by hand.
import type {
  AddonServerToClientEventName,
  AddonServerToClientEventArgs,
  AddonClientToServerWebsocketMessage,
  AddonServerToClientWebsocketMessage,
} from '@ogi-sdk/connect';

type SendEventProxyMethod<Event extends AddonServerToClientEventName> = (
  ...args: AddonServerToClientEventArgs[Event]
) => Promise<AddonClientToServerWebsocketMessage>;

type CamelCaseEvent<Event extends string> =
  Event extends `${infer Head}-${infer Tail}`
    ? `${Head}${Capitalize<CamelCaseEvent<Tail>>}`
    : Event;

type SendEventProxyMethods = {
  [Event in AddonServerToClientEventName as CamelCaseEvent<Event>]: SendEventProxyMethod<Event>;
};

export type SendEventProxy = SendEventProxyMethods & {
  noResponse: SendEventProxyMethods;
};

type EventMessagePackerMap = {
  [Event in AddonServerToClientEventName]: (
    args: AddonServerToClientEventArgs[Event]
  ) => Omit<AddonServerToClientWebsocketMessage<Event>, 'event'>;
};

interface EventMessagePackers extends EventMessagePackerMap {}

const eventMessagePackers: EventMessagePackerMap = {
  'authenticate': ([args]) => ({ args }),
  'configure': ([args]) => ({ args }),
  'config-update': ([args]) => ({ args }),
  'launch-app': ([args]) => ({ args }),
  'search': ([args]) => ({ args }),
  'setup': ([args]) => ({ args }),
  'response': ([id, response, statusError]) => ({ id, args: response, statusError }),
  'library-search': ([args]) => ({ args }),
  'check-for-updates': ([args]) => ({ args }),
  'task-run': ([args]) => ({ args }),
  'game-details': ([args]) => ({ args }),
  'request-dl': ([appID, info]) => ({ args: { appID, info } }),
  'catalog': () => ({ args: undefined }),
};
const _eventMessagePackersCheck: EventMessagePackers = eventMessagePackers;
void _eventMessagePackersCheck;

const toCamelCaseEvent = (event: string): string => {
  return event.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
};

export const eventAliases = Object.keys(eventMessagePackers).reduce(
  (aliases, event) => {
    aliases[toCamelCaseEvent(event)] = event as AddonServerToClientEventName;
    return aliases;
  },
  {} as Record<string, AddonServerToClientEventName>
);

export const buildEventMessage = <Event extends AddonServerToClientEventName>(
  event: Event,
  args: AddonServerToClientEventArgs[Event]
): AddonServerToClientWebsocketMessage<Event> => {
  const packer = eventMessagePackers[event] as unknown as (
    args: AddonServerToClientEventArgs[Event]
  ) => Omit<AddonServerToClientWebsocketMessage<Event>, 'event'>;
  return {
    event,
    ...packer(args),
  };
};
