import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { addonProtocol, type ServerCommandPack } from '../../connection/lib/protocol';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDir, '..');
const outputPath = join(packageRoot, 'lib', '_generated', 'event-proxy.ts');

const entries = Object.entries(addonProtocol.serverToAddon);

const packerForPack = (pack: ServerCommandPack): string => {
  if (pack.type === 'none') return '() => ({ args: undefined })';
  if (pack.type === 'response') {
    return '([id, response, statusError]) => ({ id, args: response, statusError })';
  }
  if (pack.type === 'object') {
    const destructured = pack.keys.join(', ');
    const object = pack.keys.join(', ');
    return `([${destructured}]) => ({ args: { ${object} } })`;
  }

  return '([args]) => ({ args })';
};

const generated = `// This file is generated by scripts/generate-event-proxy.ts. Do not edit by hand.
import type {
  AddonServerToClientEventName,
  AddonServerToClientEventArgs,
  AddonClientToServerWebsocketMessage,
  AddonServerToClientWebsocketMessage,
} from '@ogi-sdk/connect';

type SendEventProxyMethod<Event extends AddonServerToClientEventName> = (
  ...args: AddonServerToClientEventArgs[Event]
) => Promise<AddonClientToServerWebsocketMessage>;

type CamelCaseEvent<Event extends string> =
  Event extends \`\${infer Head}-\${infer Tail}\`
    ? \`\${Head}\${Capitalize<CamelCaseEvent<Tail>>}\`
    : Event;

type SendEventProxyMethods = {
  [Event in AddonServerToClientEventName as CamelCaseEvent<Event>]: SendEventProxyMethod<Event>;
};

export type SendEventProxy = SendEventProxyMethods & {
  noResponse: SendEventProxyMethods;
};

type EventMessagePackerMap = {
  [Event in AddonServerToClientEventName]: (
    args: AddonServerToClientEventArgs[Event]
  ) => Omit<AddonServerToClientWebsocketMessage<Event>, 'event'>;
};

interface EventMessagePackers extends EventMessagePackerMap {}

const eventMessagePackers: EventMessagePackerMap = {
${entries.map(([event, spec]) => `  '${event}': ${packerForPack(spec.pack)},`).join('\n')}
};
const _eventMessagePackersCheck: EventMessagePackers = eventMessagePackers;
void _eventMessagePackersCheck;

const toCamelCaseEvent = (event: string): string => {
  return event.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
};

export const eventAliases = Object.keys(eventMessagePackers).reduce(
  (aliases, event) => {
    aliases[toCamelCaseEvent(event)] = event as AddonServerToClientEventName;
    return aliases;
  },
  {} as Record<string, AddonServerToClientEventName>
);

export const buildEventMessage = <Event extends AddonServerToClientEventName>(
  event: Event,
  args: AddonServerToClientEventArgs[Event]
): AddonServerToClientWebsocketMessage<Event> => {
  const packer = eventMessagePackers[event] as unknown as (
    args: AddonServerToClientEventArgs[Event]
  ) => Omit<AddonServerToClientWebsocketMessage<Event>, 'event'>;
  return {
    event,
    ...packer(args),
  };
};
`;

await Bun.write(outputPath, generated);
console.log(`Generated ${outputPath}`);
