import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDir, '..');
const repoRoot = join(packageRoot, '..', '..');
const addonMainPath = join(repoRoot, 'packages', 'ogi-addon', 'src', 'main.ts');
const outputPath = join(packageRoot, 'lib', '_generated', 'event-proxy.ts');

const source = await Bun.file(addonMainPath).text();

const serverEventUnion = source.match(
  /export type OGIAddonServerSentEvent =([\s\S]*?);/
);

if (!serverEventUnion) {
  throw new Error('Could not find OGIAddonServerSentEvent in ogi-addon');
}

const events = [...serverEventUnion[1]!.matchAll(/'([^']+)'/g)].map(
  (match) => match[1]!
);

const camelCaseEvent = (event: string): string => {
  return event.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
};

const listenerEvents = new Set(
  [
    ...source.matchAll(/^\s*'([^']+)': \(/gm),
    ...source.matchAll(/^\s*(\w+): \(/gm),
  ]
    .map((match) => match[1])
    .filter(Boolean)
);

const argsTypeForEvent = (event: string): string => {
  if (event === 'authenticate') return '[config?: unknown]';
  if (event === 'configure') return '[config: ConfigurationFile]';
  if (event === 'config-update') return '[config: ConfigurationFile]';
  if (event === 'response')
    return '[id: string, response?: unknown, statusError?: string]';
  if (event === 'task-run') return '[task: TaskRunArgs]';
  if (listenerEvents.has(event)) return `ListenerEventArgs<'${event}'>`;

  throw new Error(`No argument mapping for server event "${event}"`);
};

const packerForEvent = (event: string): string => {
  if (event === 'catalog') return '() => ({ args: undefined })';
  if (event === 'request-dl')
    return '([appID, info]) => ({ args: { appID, info } })';
  if (event === 'response') {
    return '([id, response, statusError]) => ({ id, args: response, statusError })';
  }

  const paramName =
    event === 'library-search'
      ? 'query'
      : event === 'game-details'
        ? 'details'
        : event === 'check-for-updates' || event === 'launch-app'
          ? 'data'
          : event === 'task-run'
            ? 'task'
            : event === 'response'
              ? 'response'
              : event === 'authenticate'
                ? 'config'
                : event === 'configure' || event === 'config-update'
                  ? 'config'
                  : event === 'search'
                    ? 'query'
                    : 'data';

  return `([${paramName}]) => ({ args: ${paramName} })`;
};

const generated = `// This file is generated by scripts/generate-event-proxy.ts. Do not edit by hand.
import type {
  EventListenerTypes,
  LibraryInfo,
  OGIAddonServerSentEvent,
  WebsocketMessageClient,
  WebsocketMessageServer,
} from 'ogi-addon';
import type { ConfigurationFile } from 'ogi-addon/config';

type ArgsBeforeEventResponse<T extends unknown[]> = T extends [
  ...infer Args,
  unknown,
]
  ? Args
  : T;

type ListenerEventArgs<Event extends keyof EventListenerTypes> =
  ArgsBeforeEventResponse<Parameters<EventListenerTypes[Event]>>;

export type TaskRunArgs = {
  manifest?: Record<string, unknown>;
  downloadPath?: string;
  name?: string;
  taskName?: string;
  libraryInfo?: LibraryInfo;
  deferID?: string;
};

export type ServerEventArgs = {
${events.map((event) => `  '${event}': ${argsTypeForEvent(event)};`).join('\n')}
};

type SendEventProxyMethod<Event extends OGIAddonServerSentEvent> = (
  ...args: ServerEventArgs[Event]
) => Promise<WebsocketMessageClient>;

type CamelCaseEvent<Event extends string> =
  Event extends \`\${infer Head}-\${infer Tail}\`
    ? \`\${Head}\${Capitalize<CamelCaseEvent<Tail>>}\`
    : Event;

type SendEventProxyMethods = {
  [Event in OGIAddonServerSentEvent as CamelCaseEvent<Event>]: SendEventProxyMethod<Event>;
};

export type SendEventProxy = SendEventProxyMethods & {
  noResponse: SendEventProxyMethods;
};

type EventMessagePackers = {
  [Event in OGIAddonServerSentEvent]: (
    args: ServerEventArgs[Event]
  ) => Omit<WebsocketMessageServer, 'event'>;
};

const eventMessagePackers: EventMessagePackers = {
${events.map((event) => `  '${event}': ${packerForEvent(event)},`).join('\n')}
};

const toCamelCaseEvent = (event: string): string => {
  return event.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase()
  );
};

export const eventAliases = Object.keys(eventMessagePackers).reduce(
  (aliases, event) => {
    aliases[toCamelCaseEvent(event)] = event as OGIAddonServerSentEvent;
    return aliases;
  },
  {} as Record<string, OGIAddonServerSentEvent>
);

export const buildEventMessage = <Event extends OGIAddonServerSentEvent>(
  event: Event,
  args: ServerEventArgs[Event]
): WebsocketMessageServer => {
  return {
    event,
    ...eventMessagePackers[event](args),
  };
};
`;

await Bun.write(outputPath, generated);
console.log(`Generated ${outputPath}`);
